#!/bin/bash
#
# Compute Assessor Scores for Hybrid Theta Reconstructions
#
# This script computes assessor scores for all reconstructed images
# generated by reconstruct_semantic_heavy_all.py (job 04_semantic_heavy_reconstruct_all.sh).
#
# For each subject, it processes:
#   - 2 theta assessors (emonet, memnet) - the assessor used to create theta
#   - 6 variants per theta assessor (original, semantic_heavy, semantic_only, balanced, structural_heavy, structural_only)
#   - 7 alpha values per variant (-1.5, -1.0, -0.5, 0, 0.5, 1.0, 1.5)
#   - ~982 images per alpha value
#
# Scores are computed with the MATCHING assessor (Emonet scores for Emonet-theta images,
# MemNet scores for MemNet-theta images). This creates 2 output files per subject:
#   - emonet_scores.pkl  (Emonet scoring images from Emonet theta)
#   - memnet_scores.pkl  (MemNet scoring images from MemNet theta)
#
# Output: results/assessor_scores/hybrid_theta/subj{XX}/
#
# Usage: sbatch 05_assessor_scores_hybrid_thetas.sh
#

#SBATCH --job-name=05_hybrid_scores
#SBATCH --ntasks=1
#SBATCH --output=/home/rothermm/brain-diffuser/logs/%x_%j.out
#SBATCH --error=/home/rothermm/brain-diffuser/logs/%x_%j.err
#SBATCH --time=06:00:00
#SBATCH --mem=32G
#SBATCH --partition=normal

# --- SETUP ---
echo "==== Job started on $(hostname) at $(date) ===="
echo "Job Name: ${SLURM_JOB_NAME}"
echo "Job ID: ${SLURM_JOB_ID}"
echo "Working Directory: $(pwd)"

# --- ENVIRONMENT ---
module purge
module load miniconda
source $CONDA_ROOT/bin/activate
eval "$(conda shell.bash hook)"
conda activate brain-diffuser
echo "Activated Conda env at: $(which python)"

# --- JOB LOGIC ---
subjects=(1 2 5 7)
overall_status=0

echo "==== Computing assessor scores for hybrid theta reconstructions ===="
echo "Subjects: ${subjects[@]}"
echo "Expected output: 2 pickle files per subject (8 total)"
echo ""

# Process all subjects sequentially
for sub in "${subjects[@]}"; do
    echo "==== Processing subject $sub at $(date) ===="
    
    python -u /home/rothermm/brain-diffuser/scripts/analysis/assessor_scores_hybrid_thetas.py \
        --sub "$sub" \
        2>&1 | tee logs/${SLURM_JOB_NAME}_sub${sub}_${SLURM_JOB_ID}.log

    if [ "${PIPESTATUS[0]}" -ne 0 ]; then
        echo "!! ERROR: Assessor scoring failed for subject $sub"
        overall_status=1
    else
        echo "✓ Successfully computed scores for subject $sub"
    fi

    echo "==== Finished subject $sub at $(date) ===="
    echo ""
done

echo "==== Job finished at $(date) with overall status: $overall_status ===="
echo ""
echo "Output files (per subject):"
echo "  - emonet_scores.pkl  (Emonet scoring Emonet-theta images)"
echo "  - memnet_scores.pkl  (MemNet scoring MemNet-theta images)"
echo ""
echo "Location: results/assessor_scores/hybrid_theta/subj{XX}/"
exit $overall_status
