#!/bin/bash
#
# Compute Assessor Scores for Hybrid Theta Reconstructions (Single Subject)
#
# This script computes assessor scores for all reconstructed images
# generated by reconstruct_semantic_heavy_all.py (job 04_semantic_heavy_reconstruct_all.sh).
#
# For the specified subject, it processes:
#   - 2 theta assessors (emonet, memnet) - the assessor used to create theta
#   - 6 variants per theta assessor (original, semantic_heavy, semantic_only, balanced, structural_heavy, structural_only)
#   - 7 alpha values per variant (-1.5, -1.0, -0.5, 0, 0.5, 1.0, 1.5)
#   - ~982 images per alpha value
#
# Scores are computed with the MATCHING assessor (Emonet scores for Emonet-theta images,
# MemNet scores for MemNet-theta images). This creates 2 output files per subject:
#   - emonet_scores.pkl  (Emonet scoring images from Emonet theta)
#   - memnet_scores.pkl  (MemNet scoring images from MemNet theta)
#
# Output: results/assessor_scores/hybrid_theta/subj{XX}/
#
# Usage: 
#   sbatch 05_assessor_scores_hybrid_thetas.sh 1    # For subject 1
#   sbatch 05_assessor_scores_hybrid_thetas.sh 2    # For subject 2
#   sbatch 05_assessor_scores_hybrid_thetas.sh 5    # For subject 5
#   sbatch 05_assessor_scores_hybrid_thetas.sh 7    # For subject 7
#
# Or submit all at once:
#   for sub in 1 2 5 7; do sbatch 05_assessor_scores_hybrid_thetas.sh $sub; done
#

#SBATCH --job-name=05_hybrid_scores_sub%a
#SBATCH --ntasks=1
#SBATCH --output=/home/rothermm/brain-diffuser/logs/%x_%j.out
#SBATCH --error=/home/rothermm/brain-diffuser/logs/%x_%j.err
#SBATCH --time=10:00:00
#SBATCH --mem=16G
#SBATCH --partition=normal

# --- SETUP ---
echo "==== Job started on $(hostname) at $(date) ===="
echo "Job Name: ${SLURM_JOB_NAME}"
echo "Job ID: ${SLURM_JOB_ID}"
echo "Working Directory: $(pwd)"

# Get subject from command line argument
if [ -z "$1" ]; then
    echo "ERROR: No subject specified!"
    echo "Usage: sbatch 05_assessor_scores_hybrid_thetas.sh <subject_number>"
    echo "Example: sbatch 05_assessor_scores_hybrid_thetas.sh 1"
    echo "Valid subjects: 1, 2, 5, 7"
    exit 1
fi

SUBJECT=$1

# Validate subject number
if [[ ! "$SUBJECT" =~ ^[1257]$ ]]; then
    echo "ERROR: Invalid subject '$SUBJECT'"
    echo "Valid subjects: 1, 2, 5, 7"
    exit 1
fi

echo "Subject: $SUBJECT"
echo ""

# --- ENVIRONMENT ---
module purge
module load miniconda
source $CONDA_ROOT/bin/activate
eval "$(conda shell.bash hook)"
conda activate brain-diffuser
echo "Activated Conda env at: $(which python)"

# --- JOB LOGIC ---
echo "==== Computing assessor scores for hybrid theta reconstructions ===="
echo "Subject: $SUBJECT"
echo "Expected output: 2 pickle files (emonet_scores.pkl, memnet_scores.pkl)"
echo ""

echo "==== Processing subject $SUBJECT at $(date) ===="

python -u /home/rothermm/brain-diffuser/scripts/analysis/assessor_scores_hybrid_thetas.py \
    --sub "$SUBJECT" \
    2>&1 | tee logs/${SLURM_JOB_NAME}_sub${SUBJECT}_${SLURM_JOB_ID}.log

job_status=$?

if [ "$job_status" -ne 0 ]; then
    echo "!! ERROR: Assessor scoring failed for subject $SUBJECT"
    exit 1
else
    echo "✓ Successfully computed scores for subject $SUBJECT"
fi

echo "==== Finished subject $SUBJECT at $(date) ===="
echo ""

echo "==== Job finished at $(date) ===="
echo ""
echo "Output files for subject $SUBJECT:"
echo "  - emonet_scores.pkl  (Emonet scoring Emonet-theta images)"
echo "  - memnet_scores.pkl  (MemNet scoring MemNet-theta images)"
echo ""
echo "Location: results/assessor_scores/hybrid_theta/subj$(printf '%02d' $SUBJECT)/"
exit $job_status
